// export const  GENERATION_ACTION_TYPE = 'GENERATION_ACTION_TYPE';

 const GENERATION = {
    FETCH:'GENERATION_FETCH',
    FETCH_ERROR:'GENERATION_FETCH_ERROR',
    FETCH_SUCCESS:'GENERATION_FETCH_SUCCESS'
};


 const DRAGON ={
    FETCH: 'DRAGON_FETCH',
    FETCH_ERROR: 'DRAGON_FETCH_ERROR',
    FETCH_SUCCESS: 'DRAGON_FETCH_SUCCESS'
};

const USERACCOUNT_DRAGONS ={
    FETCH: 'USERACCOUNT_DRAGON_FETCH',
    FETCH_ERROR: 'USERACCOUNT_DRAGON_FETCH_ERROR',
    FETCH_SUCCESS: 'USERACCOUNT_DRAGON_FETCH_SUCCESS'
};


const USERACCOUNT ={
    FETCH: 'USERACCOUNT_FETCH',
    FETCH_ERROR: 'USERACCOUNT_FETCH_ERROR',
    FETCH_SUCCESS:' USERACCOUNT_FETCH_SUCCESS',
    FETCH_LOGOUT_SUCCESS: 'USERACCOUNT_FETCH_LOGOUT_SUCCESS' ,
   FETCH_AUTHENTICATED_SUCCESS: 'USERACCOUNT_FETCH_AUTHENTICATED_SUCCESS'
};

const USERACCOUNT_INFO ={
    FETCH: 'USERACCOUNT_FETCH',
    FETCH_ERROR: 'USERACCOUNT_FETCH_ERROR',
    FETCH_SUCCESS: 'USERACCOUNT_FETCH_SUCCESS'
};

 export{GENERATION, DRAGON, USERACCOUNT, USERACCOUNT_INFO, USERACCOUNT_DRAGONS};
